# Generated by Django 5.2.4 on 2025-07-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('view', 'View'), ('delete', 'Delete')], max_length=10)),
            ],
            options={
                'unique_together': {('name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('seller', 'Seller')], max_length=10)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
